posgradmin/posgradmin/urls.py
from django.urls import path, re_path, include
from django.contrib import admin


from posgradmin.views import PerfilEditar, PerfilDetail, \
    PerfilAcademicoDetail, PerfilProfesorDetail, PerfilProfesorEditar,\
    AcademicoActividadView, AcademicoResumenCVView, AcademicoPerfilView, \
    InicioView, \
    GradoAcademicoAgregar, GradoAcademicoEliminar, InstitucionAgregarView, \
    AdscripcionEliminar, AdscripcionAgregar, AsociacionAgregar, \
    AcademicoSortableView, \
    UserDetail, PerfilComite, \
    EstudianteFichaDetail, AcademicoInvitar, AcademicoSearch, \
    TogglePerfilEditar, UploadAssets, CursoIndexView, CursoDetalle

from posgradmin.views_academico import \
    EligeAsignatura, SolicitaCurso, PanelConvocatoriaCursos,\
    AcademicoAutocomplete, CursoView, MisCursos, ProponerAsignatura, CursoConstancia, CursoConstanciaEstudiante

from django.conf.urls.static import static

from posgradmin.settings import MEDIA_ROOT, MEDIA_URL, STATIC_ROOT, STATIC_URL

urlpatterns = [

    path("__reload__/", include("django_browser_reload.urls")),

    path('admin/upload_assets/', UploadAssets.as_view(), name='upload_assets'),
    
    re_path(r'^admin/posgradmin/toggle_perfil_editar/', TogglePerfilEditar.as_view(),
        name="toggle_perfil_editar"),

    re_path(r'^admin/posgradmin/academico/invitar/', AcademicoInvitar.as_view(),
        name="academico_invitar"),

    re_path(r'^admin/', admin.site.urls),

    re_path('^accounts/', include('allauth.urls')),

    path('estudiante/<slug:slug>',
        EstudianteFichaDetail.as_view(),
        name='estudiante_ficha'),
    
    re_path(r'^export_action/', include(("export_action.urls", 'export_action'),
                                     namespace="export_action")),

    re_path(r'^institucion/agregar/(?P<devolver>[\w-]+)/',
        InstitucionAgregarView.as_view(),
        name="agregar_institucion"),

    re_path(r'^inicio/academico/perfil',
        AcademicoPerfilView.as_view(),
        name="academico_perfil"),

    re_path(r'^inicio/academico/resumen',
        AcademicoResumenCVView.as_view(),
        name="academico_resumen"),

    re_path(r'^inicio/academico/actividad',
        AcademicoActividadView.as_view(),
        name="academico_actividad"),

    re_path(r'^inicio/perfil/editar$',
        PerfilEditar.as_view(),
        name="editar_perfil"),

    re_path(r'^inicio/perfil/eliminar-grado/(?P<pk>[0-9]+)$',
        GradoAcademicoEliminar.as_view(),
        name="eliminar_grado"),

    re_path(r'^inicio/perfil/eliminar-adscripcion/(?P<pk>[0-9]+)$',
        AdscripcionEliminar.as_view(),
        name="eliminar_adscripcion"),

    re_path(r'^inicio/perfil/agregar-grado$',
        GradoAcademicoAgregar.as_view(),
        name="agregar_grado"),

    re_path(r'^inicio/perfil/agregar-adscripcion$',
        AdscripcionAgregar.as_view(),
        name="agregar_adscripcion"),

    re_path(r'^inicio/perfil/agregar-asociacion$',
        AsociacionAgregar.as_view(),
        name="agregar_asociacion"),

    re_path(r'^inicio/perfil/comite/(?P<username>.+)$',
        PerfilComite.as_view(),
        name="perfilcomite"),

    re_path(r'^inicio/perfil/$',
        PerfilDetail.as_view(),
        name='perfil'),

    re_path(r'^inicio/perfil-academico/$',
        PerfilAcademicoDetail.as_view(),
        name='perfil_academico'),

    re_path(r'^inicio/perfil-profesor/$',
        PerfilProfesorDetail.as_view(),
        name='perfil_profesor'),

    re_path(r'^inicio/perfil-profesor/editar',
        PerfilProfesorEditar.as_view(),
        name="perfil_profesor_editar"),

    re_path(r'^inicio/academicos/$',
        AcademicoSortableView.as_view(),
        name="lista_academicos"),

    re_path(r'^inicio/academicos/search/$',
        AcademicoSearch.as_view(),
        name="academicos_search"),

    re_path(r'^inicio/$',
        InicioView.as_view(),
        name="inicio"),

    # re_path(r'^inicio/sesiones/(?P<pk>[0-9]+)/$',
    #     SesionDetail.as_view(),
    #     name="sesion_detail"),

    # re_path(r'^inicio/sesiones/$',
    #     SesionesListView.as_view(),
    #     name='lista_sesiones'),

    re_path(r'^inicio/usuario/(?P<pk>[0-9]+)/$',
        UserDetail.as_view(),
        name="user_detail"),

    re_path('^inicio/', InicioView.as_view()),

    re_path(
        r'^academico-autocomplete/$',
        AcademicoAutocomplete.as_view(),
        name='academico-autocomplete',
        ),


    re_path('^convocatoria-cursos/(?P<pk>[0-9]+)/asignatura/elegir/',
        EligeAsignatura.as_view(),
        name="elige_asignatura"),

    re_path('^convocatoria-cursos/(?P<pk>[0-9]+)/asignatura/(?P<as_id>[0-9]+)/',
        SolicitaCurso.as_view(),
        name="solicita_curso"),

    re_path('^convocatoria-cursos/(?P<pk>[0-9]+)/panel/',
        PanelConvocatoriaCursos.as_view(),
        name="panel_convocatoria_cursos"),
    
    re_path('^cursos/mis/',
        MisCursos.as_view(),
        name="mis_cursos"),

    re_path('^cursos/(?P<pk>[0-9]+)/constancia-estudiante/',
        CursoConstanciaEstudiante.as_view(),
        name="curso_constancia_estudiante"),

    re_path('^cursos/(?P<pk>[0-9]+)/constancia/',
        CursoConstancia.as_view(),
        name="curso_constancia"),

    path('cursos/detalle/<int:curso_id>/', CursoDetalle.as_view(),
         name='curso_detalle'),
    
    re_path('^cursos/(?P<pk>[0-9]+)/',
        CursoView.as_view(),
        name="curso"),


    
    path('cursos/', CursoIndexView.as_view(),
         name='cursos'),

    

    re_path('^proponer-asignatura/',
        ProponerAsignatura.as_view(),
        name="proponer_asignatura"),


] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

# ./coordinacion/alimentar_saep.md
# ./coordinacion/oficios_para_firma_de_los_miembros_del_Jurado.md

posgradmin/posgradmin/models.py
# coding: utf-8
import os
import pandas as pd
from pandas.plotting import parallel_coordinates

import datetime

from django.template.defaultfilters import slugify
from django.db import models
from django.db.models import Q

from django.contrib.auth.models import User

from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from .settings import MEDIA_URL, \
    APP_PREFIX, MEDIA_ROOT, BASE_DIR

from wordcloud import WordCloud

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from tempfile import NamedTemporaryFile
from django.template.loader import render_to_string
from sh import rm
import subprocess
import pathlib
from pdfrw import PdfReader, PdfWriter, PageMerge


def nota_path(instance, filename):
    (root, ext) = os.path.splitext(filename)
    return os.path.join(u'nota_%s_%s' % (instance.id, slugify(root) + ext))


class Nota(models.Model):
    asunto = models.CharField(max_length=100)
    nota = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User,
                              on_delete=models.CASCADE, null=True, blank=True)

    archivo = models.FileField(upload_to=nota_path,
                               null=True, blank=True)
    estado = models.CharField(max_length=40,
                              default='memo',
                              choices=((u"memo",
                                        u"memo"),
                                       ("denuncia",
                                        "denuncia"),
                                       (u"atendida",
                                        u"atendida"),
                                       (u"solicitud",
                                        u"solicitud")))


    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return "%s, fecha: %s" % (self.autor,
                                      self.fecha.strftime("%Y-%m-%d %H:%M"))




class ConvocatoriaCurso(models.Model):
    year = models.PositiveSmallIntegerField("Año")
    semestre = models.PositiveSmallIntegerField(
        choices=((1, 1), (2, 2)))
    status = models.CharField(max_length=10,
            choices=[('abierta', 'abierta'),
                     ('rev CA', 'revisión CA'),
                     ('cerrada', 'cerrada')])

    notas = GenericRelation(Nota,
                           related_query_name='convocatoria_curso')


    def __str__(self):
        if self.status == 'abierta':
            status = '(abierta)'
        else:
            status = ''
        return u"%s-%s %s" % (self.year,
                              self.semestre,
                              status)

    class Meta:
        verbose_name_plural = "Convocatorias para cursos"
        unique_together = ('year', 'semestre')
        ordering = ['year', 'semestre', ]


class Institucion(models.Model):
    nombre = models.CharField("Institución u Organización", max_length=150)
    suborganizacion = models.CharField(
        "Dependencia, Entidad o Departamento", max_length=150)
    pais = models.CharField("País", max_length=100, blank=True)
    estado = models.CharField(max_length=100, blank=True)
    dependencia_UNAM = models.BooleanField(default=False)
    entidad_PCS = models.BooleanField(default=False)

    def __str__(self):
        if self.entidad_PCS:
            pcs = "(entidad del PCS)"
        else:
            pcs = ""
        return u"%s, %s %s" % (self.nombre, self.suborganizacion, pcs)

    class Meta:
        verbose_name_plural = "instituciones"
        unique_together = ('nombre', 'suborganizacion', 'estado', 'pais')
        ordering = ['nombre', 'suborganizacion', ]


class CampoConocimiento(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return u"%s" % self.nombre

    class Meta:
        verbose_name_plural = "campos de conocimiento"


class LineaInvestigacion(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return u"%s" % self.nombre

    class Meta:
        verbose_name_plural = "líneas de investigación"


def headshot_path(instance, filename):
    extension = filename.split('.')[-1]
    return u'headshots/%s.%s' % (instance.user.id, extension)


class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    curp = models.CharField("CURP. Si usted es extranjero(a) y no cuenta con "
                            + "este dato, ingresar la palabra extranjero(a)",
                            max_length=100)
    rfc = models.CharField("RFC. Si usted es extranjero(a) y no cuenta con "
                           + "este dato, ingresar la palabra extranjero(a)",
                           max_length=100)

    CVU = models.CharField(u"Número de CVU",
                           max_length=100, blank=True, null=True)

    telefono = models.CharField(max_length=100)
    telefono_movil = models.CharField(max_length=100, blank=True)

    direccion1 = models.CharField("dirección del lugar de trabajo",
                                  max_length=350)

    codigo_postal = models.PositiveSmallIntegerField(default=0)

    website = models.CharField(max_length=200, blank=True)

    genero = models.CharField(max_length=1, choices=(('M', 'masculino'),
                                                     ('F', 'femenino')))

    nacionalidad = models.CharField(max_length=100)

    fecha_nacimiento = models.DateField('fecha de nacimiento',
                                        blank=True, null=True)

    headshot = models.ImageField("fotografía",
                                 upload_to=headshot_path,
                                 blank=True, null=True)

    notas = GenericRelation(Nota,
                           related_query_name='perfil')


    def __str__(self):
        return u"%s" % self.user.get_full_name()

    def __repr__(self):
        return self.__str__()

    class Meta:
        verbose_name_plural = "Perfiles Personales"
        ordering = ['user__first_name', 'user__last_name', ]


    def asociado_PCS(self):
        for a in self.adscripcion_set.all():
            if a.institucion.entidad_PCS or a.asociacion_PCS:
                return True
        return False

    def adscripcion(self):
        return self.adscripcion_set.filter(asociacion_PCS=False)

    def adscripcion_ok(self):
        """
        si tiene adscripciones virtuales, debe tener una real tambien
        """

        if self.adscripcion_set.filter(asociacion_PCS=True).count() > 0:
            # ha registrado virtuales
            if self.adscripcion_set.filter(asociacion_PCS=False).count() > 0:
                # y reales
                return True
            else:
                # pero no reales
                return False
        else:
            # no ha registrado virtuales
            if self.adscripcion_set.count() > 0:
                # pero ha registrado
                return True
            else:
                # no ha registrado ninguna!
                return False

    def perfil_publico_anchor(self):
        return u"""<a href='%sinicio/perfil/publico/%s'>%s</a>""" % (
            APP_PREFIX,
            self.user.get_username(), self.__str__())

    def perfil_comite_anchor(self):
        return u"""<a href='%sinicio/perfil/comite/%s'>%s</a>""" % (
            APP_PREFIX,
            self.user.get_username(), self.__str__())



class Invitado(models.Model):
    nombre = models.CharField(max_length=333)
    correo = models.EmailField(blank=True, null=True)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.nombre


class GradoAcademico(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    nivel = models.CharField(max_length=15,
                             choices=(('licenciatura', 'licenciatura'),
                                      ('maestria', 'maestria'),
                                      ('doctorado', 'doctorado')))

    grado_obtenido = models.CharField(max_length=100)

    institucion = models.ForeignKey(Institucion, on_delete=models.CASCADE)

    fecha_obtencion = models.DateField("Fecha de obtención de grado")

    def __str__(self):
        return u"%s @ %s" % (self.grado_obtenido, self.institucion)

    class Meta:
        verbose_name_plural = "Grados académicos"
        ordering = ("-fecha_obtencion",)


class Estudiante(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cuenta = models.CharField(max_length=100)

    estado = models.CharField(
        max_length=25,
        choices=(
            ('inscrito', 'inscrito'),
            ('egresado', 'egresado'),
            ('graduado', 'graduado'),
            ('indeterminado', u'indeterminado'),
            ('baja', 'baja'),
            (u'suspensión 1 sem', u'suspensión 1 sem'),
            (u'suspensión 2 sem', u'suspensión 2 sem'),
            ('ausente', 'ausente'),
        ),
        null=True, blank=True)

    plan = models.CharField(
        max_length=20,
        choices=[("Maestría", "Maestría"),
                 ("Doctorado", "Doctorado")],
        default="Maestría"
    )

    doctorado_directo = models.BooleanField(default=False)
    opcion_titulacion = models.BooleanField("Opción a titulación",
                                            default=False)

    campo_conocimiento = models.ForeignKey(CampoConocimiento,
                                           blank=True, null=True,
                                           on_delete=models.CASCADE)
    lineas_investigacion = models.ForeignKey(LineaInvestigacion,

posgradmin/posgradmin/templates/posgradmin/asunto_list.html
{% extends "posgradmin/posgradmin_base.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  {% for crumb in breadcrumbs %}  
  &rsaquo; <a href="{{ crumb.0 }}">{{ crumb.1 }}</a>
  {% endfor %}

  &rsaquo; <a href="/inicio">Inicio</a>
  &rsaquo; <a href="/inicio/asuntos/">Asuntos</a>
  &rsaquo; <a href="/inicio/asuntos/nuevo">Nuevo asunto</a>   
</div>
{% endblock %}


{% block content %}

<h2>Asuntos</h2>

<a href="nuevo/">nuevo asunto</a>
<ul>
  {% for asunto in object_list %}
  <li>{{ asunto }}</li>
  {% endfor %}
</ul>

<script>
$(document).ready(function() {
    $('.dateinput').datepicker({ dateFormat: 'yy-mm-dd'});
}); 
</script>
{% endblock %}

posgradmin/posgradmin/templates/posgradmin/curso_list.html
{% extends "posgradmin/posgradmin_base.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  {% for crumb in breadcrumbs %}
  &rsaquo; <a href="{{ crumb.0 }}">{{ crumb.1 }}</a>
  {% endfor %}

  &rsaquo; <a href="/inicio">Inicio</a>
  &rsaquo; <a href="/inicio/cursos/mis_cursos">Mis cursos</a>

</div>
{% endblock %}


{% block content %}

<h2>Mis cursos</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Denominación</th>
      <th>Clave</th>
      <th>Semestre</th>
      <th>Campo de Conocimiento</th>
    </tr>
  </thead>

  <tbody>
    {% for curso in object_list %}
    <tr>
      <th>{{ curso.denominacion }} </th>
      <th>{{ curso.clave }}</th>
      <th>{{ curso.semestre }}</th>
      <th>{{ curso.campo_conocimiento }}</th>      
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

posgradmin/posgradmin/templates/posgradmin/cursos_index.html
{% extends "posgradmin/posgradmin_base.html" %}
{% load markdownify %}

{% block title %}
Cursos y horarios
{% endblock %}


{% block content %}
<h1>Cursos y horarios</h1>

{{ cursos_md|markdownify }}

{% endblock %}

posgradmin/posgradmin/templates/posgradmin/estudiante_list.html
{% extends "posgradmin/posgradmin_base.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  {% for crumb in breadcrumbs %}
  &rsaquo; <a href="{{ crumb.0 }}">{{ crumb.1 }}</a>
  {% endfor %}

  &rsaquo; <a href="{% url 'inicio' %}">Inicio</a>
  &rsaquo; <a href="{% url 'lista_estudiantes' %}">Estudiantes</a>
</div>
{% endblock %}





{% block content %}

<h2>Estudiantes</h2>

<a href="{% url 'cargar_estudiantes' %}">Cargar lote de estudiantes</a>
<hr>

<form action="" accept-charset="UTF-8">
  <input name="search">
  <input type="submit">
</form>
{% include 'sortable_listview/sort_links.html' %}

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>nombre</th>
      <th>estado</th>
      <th>plan</th>
      <th>entidad</th>
      <th>ingreso</th>
      <th>semestre</th>
    </tr>
  </thead>

  <tbody>
    {% for estudiante in object_list %}

    <tr>
      <td><a href="{% url 'user_detail' estudiante.user.id %}">
	  {{ estudiante.user.id }}</a></td>
      <td><a href="{% url 'user_detail' estudiante.user.id %}">{{ estudiante.user.get_full_name }}</a></td>
      <td>{{ estudiante.estado|default:'' }}</td>
      <td>{{ estudiante.plan|default:'' }}</td>
      <td>{{ estudiante.entidad|default:'' }}</td>
      <td>{{ estudiante.ingreso|default:'' }}</td>
      <td>{{ estudiante.semestre|default:'' }}</a></td>
    </tr>

  {% endfor %}
  </tbody>
</table>
  {% include 'sortable_listview/pagination.html' %}

{% endblock %}

posgradmin/posgradmin/templates/posgradmin/grado_academico_agregar.html
{% extends "posgradmin/posgradmin_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>{{ user.get_full_name }}</h1>

<hr>
<br />

{% crispy form %}


<script>
$(document).ready(function() {
    $('.dateinput').datepicker({ dateFormat: 'yy-mm-dd'});
}); 
</script>

{% endblock %}

posgradmin/posgradmin/templates/posgradmin/inicio_academico.html
{% if not user.academico.perfil_profesor_completo %}
<div class="bg-red-100 p-4 m-2">
  Para acreditarse como profesor falta cubrir los siguientes requisitos:
  <ul class="m-2">
    {% if not user.academico.ultimo_grado %}<li> - Anexar último grado académico </li>{% endif %}
    {% if not user.academico.anexo_CV %}<li> - Anexar <i>currículum vitae</i></li> {% endif %}
  </ul>

  <a class="bg-gray-100 p-2 m-2 rounded-lg"
     href="{% url 'perfil_profesor_editar' %}">editar perfil de profesor</a>
</div>
{% endif %}


{% if convocatorias_curso %}
{% for c in convocatorias_curso %}
<div class="bg-yellow-50 m-2 p-2 shadow">
  <h1 class="text-2xl">Convocatoria</h1>
  <div class="text-lg font-semibold text-green-900 m-4">
    Para impartir cursos en el semestre {{ c.year}}-{{ c.semestre }}</div>
  <a class="bg-gray-100 p-2 m-2 rounded-lg"
     href="{% url 'elige_asignatura' c.id %}">registra una solicitud</a>
</div>
{% endfor %}
{% endif %}



{% if user.academico.comite_academico %}
<div class="bg-indigo-100 m-2 p-2 shadow flex flex-col">
{% for c in convocatorias_revision %}
<a href="{% url 'panel_convocatoria_cursos' c.id %}">Panel para revisión de la Convocatoria de Cursos {{ c }}</a>
{% endfor %}
</div>
{% endif %}

posgradmin/posgradmin/templates/posgradmin/institucion_agregar.html
{% extends "posgradmin/posgradmin_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
   {% crispy form %}
{% endblock %}

posgradmin/posgradmin/templates/posgradmin/perfil_personal_comite.html
<div class="panel-body">



      <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">
	  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
	  Datos Personales</h3>
      </div>
      <div class="panel-body">

	<div class="media">
	  <div class="media-left media-middle">
	    {% if U.perfil.headshot %}
	    <img alt="" class="media-object"
		 width="150px"
		 src="{{ U.perfil.headshot.url }}" />

	    {% endif %}
	  </div>
	  <div class="media-body">

	    <ul class="list-group">
	      <li class="list-group-item"><strong>Fecha de Nacimiento</strong>
		{{ U.perfil.fecha_nacimiento|default:"" }}</li>
	      <li class="list-group-item"><strong>Genero</strong> {{ U.perfil.genero }}</li>
	      <li class="list-group-item"><strong>Nacionalidad</strong> {{ U.perfil.nacionalidad }}</li>
	      <li class="list-group-item"><strong>CURP</strong> {{ U.perfil.curp }}</li>
	      <li class="list-group-item"><strong>RFC</strong> {{ U.perfil.rfc }}</li>
	    </ul>
	  </div>
	</div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
	<h3 class="panel-title">
	  <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
	  Información de contacto
	</h3>
      </div>
      <div class="panel-body">
	<ul class="list-group">
	  <li class="list-group-item"><strong>Teléfono</strong> {{ U.perfil.telefono }}</li>
	  <li class="list-group-item"><strong>Teléfono Móvil</strong> {{ U.perfil.telefono_movil }}</li>
	  <li class="list-group-item"><strong>email</strong> <a href="mailto:{{ U.email }}">{{ U.email }}</a></li>
	  <li class="list-group-item"><strong>Sitio Web</strong> {{ U.perfil.website }}</li>
	  <li class="list-group-item"><strong>Dirección</Strong> {{ U.perfil.direccion1 }}</li>
	  <li class="list-group-item"><strong>Código Postal</strong> {{ U.perfil.codigo_postal|default:"" }}</li>
	</ul>
      </div>
    </div>






  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
	<span class="glyphicon glyphicon-tree-conifer" aria-hidden="true"></span>
	Adscripción
      </h3>
    </div>

    <div class="panel-body">
      <ul class="list-group">
	{% for ad in U.perfil.adscripcion_set.all %}
	<li class="list-group-item">
	  {{ ad }}
	  {% if ad.catedra_conacyt %}
	  <br />
	  Cátedra CONACYT
	  {% endif %}
	  <br />
	  {% if not ad.asociacion_PCS %}
	  {{ ad.nombramiento }} desde {{ ad.anno_nombramiento }}
	  {% endif %}
	</li>
	{% endfor %}
      </ul>
    </div>
  </div>



  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
	<span class="glyphicon glyphicon-certificate" aria-hidden="true"></span>
	Grados Académicos
      </h3>
    </div>
    <div class="panel-body">
      <ul class="list-group">
	{% for grado in U.gradoacademico_set.all %}
	<li class="list-group-item">
	  <strong>{{ grado.grado_obtenido }} </strong>@ {{ grado.institucion }}
	  <p class="list-group-item-text">
	    nivel {{ grado.nivel }}
	    obtenido el {{ grado.fecha_obtencion }}<br />
	  </p>

	</li>
	{% empty %}
	<li class="list-group-item">&nbsp;
	</li>
	{% endfor %}
      </ul>
    </div>
  </div>


</div>

posgradmin/posgradmin/templates/posgradmin/posgradmin_base.html
{% extends "base.html" %}
{% load admin_urls %}


{% block title %}{% endblock %}

{% block extrahead %}

{% endblock %}




{% block usertools %}

{% endblock %}


{% block breadcrumbs %}
<div class="breadcrumbs">
  {% for crumb in breadcrumbs %}
  &rsaquo; <a href="{{ crumb.0 }}">{{ crumb.1 }}</a>
  {% endfor %}
</div>
{% endblock %}

{% block messages %}{% endblock %}

{% block pretitle %}{% endblock %}

{% block content %}
{% endblock %}

{% block object-tools %}{% endblock %}

{% block sidebar %}{% endblock %}
{% block footer %}{% endblock %}

posgradmin/posgradmin/templates/posgradmin/solicitud_agendar.html
{% extends "posgradmin/solicitud_detail.html" %}
{% load crispy_forms_tags %}

{% block dictamen_form %}
<h2>Agendar para Sesión del Comité Académico</h2>
   {% crispy form %}
{% endblock %}